version: '3.8'

services:
  bot:
    image: "${BOT_IMAGE_NAME:-tgbot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tgbot-container}"
    stop_signal: SIGINT
    build:
      context: .
    network_mode: "host"
    working_dir: "/usr/src/app/${BOT_NAME:-tgbot}"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-tgbot}
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: 'redis:7.2.4'
    ports:
      - '6379:6379'
    logging:
      options:
        max-size: "10m"
        max-file: "3"
