"""column advance is removed

Revision ID: 16cac16c78bd
Revises: 816059f1dcf4
Create Date: 2024-04-27 15:51:11.615970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16cac16c78bd'
down_revision = '816059f1dcf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'advance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('advance', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
