"""initial

Revision ID: 441af8c4d821
Revises: 34906c8f924c
Create Date: 2023-11-11 17:35:58.546854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441af8c4d821'
down_revision = '34906c8f924c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('resource', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('entry_point', sa.String(), nullable=False))
    op.add_column('registrations', sa.Column('advance', sa.String(), nullable=False))
    op.drop_column('registrations', 'is_blocked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('registrations', 'advance')
    op.drop_column('registrations', 'entry_point')
    op.drop_column('registrations', 'resource')
    # ### end Alembic commands ###
