"""added resource to clients

Revision ID: 494f6a7bf7ae
Revises: 947350ff5b18
Create Date: 2023-12-11 06:27:46.537946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494f6a7bf7ae'
down_revision = '947350ff5b18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('resource', sa.String(), nullable=True))
    op.drop_column('registrations', 'resource')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('resource', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('clients', 'resource')
    # ### end Alembic commands ###
