"""new column service duration in ClientsDB

Revision ID: 72c026b1b96f
Revises: 94f61f918560
Create Date: 2023-11-19 20:10:21.244899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c026b1b96f'
down_revision = '94f61f918560'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('service_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'service_duration')
    # ### end Alembic commands ###
