"""mailings client_groups to client_group

Revision ID: 947350ff5b18
Revises: 72c026b1b96f
Create Date: 2023-11-27 17:00:09.862280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947350ff5b18'
down_revision = '72c026b1b96f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailings', sa.Column('client_group', sa.String(), nullable=False))
    op.drop_column('mailings', 'client_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailings', sa.Column('client_groups', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('mailings', 'client_group')
    # ### end Alembic commands ###
